nodeVersion: 25.9.0
engineStrict: true

allowBuilds:
  '@keqingmoe/tree-sitter': true
  esbuild: true
  tree-sitter-rust: true
onlyBuiltDependencies:
  - '@keqingmoe/tree-sitter'
  - esbuild
  - tree-sitter-query
  - tree-sitter-rust
